name: "Build Android app"

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name to run the action on'
        required: true
        default: 'main'
    # Uncomment the following lines if you also want to trigger on push and pull_request events
    # push:
    # pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Node  
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      # Debug build steps
      - name: Bundle React Native code for Debug
        run: npm run react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/

      # Debug build steps
      - name: Build application (Debug)
        run: |
          echo "Building Debug APK on branch ${{ github.event.inputs.branch }}"
          cd android
          ./gradlew assembleDebug
      - name: Upload application (Debug)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 3

      # Release build steps
      - name: Bundle React Native code for Release
        run: npm run react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle

      # Release build steps
      - name: Build application (Release)
        run: |
          echo "Building Release APK on branch ${{ github.event.inputs.branch }}"
          cd android
          ./gradlew assembleRelease
      - name: Upload application (Release)
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/app-release.apk
          retention-days: 3
