name: 'Build iOS app'

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name to run the action on'
        required: true
        default: 'main'
        
jobs:
  build_with_signing:
    runs-on: macos-latest
    steps:
      # this was more debug as was curious what came pre-installed
      - name: check Xcode version
        run: /usr/bin/xcodebuild -version

      - name: checkout repository
        uses: actions/checkout@v3

      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_PART1: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64_1 }}
          BUILD_PROVISION_PROFILE_PART2: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64_2 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.cer
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_PART1$BUILD_PROVISION_PROFILE_PART2" | base64 --decode -o $PP_PATH
          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH
          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install
      - name: Build and Archive the project
        run: |
          cd ios
          xcodebuild -workspace BuildApp.xcworkspace \
          -scheme "BuildApp" \
          -configuration Debug \
          -destination generic/platform=iOS \
          archive \
          -archivePath ./build/buildapp.xcarchive   
      - name: export ipa
        run: |
          cd ios
          xcodebuild -exportOptionsPlist ./build/buildapp.xcarchive/Info.plist -exportArchive -archivePath ./build/buildapp.xcarchive  -exportPath ./build
      - name: Upload application
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: ios/build/BuildApp.ipa
          retention-days: 3
